name: CD with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Github Actions의 워크플로워 runner 환경

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle Wrapper -> jar 파일 생성
        run: |
          chmod 544 ./gradlew
          ./gradlew build -x test


      - name: Transfer Build File using SCP -> jar 파일 원격 서버 복사
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/hackathon/build/libs/"   # ⬅️ 경로 맞추기


      - name: docker compose up -> make (mysql,spring, nginx)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/hackathon
            git fetch --all
            git reset --hard origin/main         # 서버에 최신 코드 반영
            docker compose down
            docker compose build spring --no-cache
            docker compose up -d spring
            docker image prune -f
    
